### ISSUE TITLE
RxJava 2.0

### ISSUE THREAD

**Issue by Wanimal** [pwittchen/ReactiveNetwork#126]
Can you speed up the development of RxJava 2.0 Version?

**Comment by pwittchen** [comment]
It's being done within #80. Currently, experimental version of the library with RxJava is available on `RxJava2.x` branch and you can play with it if you want to. I'm going to release separate artifact with RxJava 2 (issue #84).

Please note, I'm not developing this project full-time. It's my side-project and I'm developing it in my free time. That's why sometimes I'm not able to publish an update every day or every week. Nevertheless, I'm trying to do my best to keep it up to date :).

**Comment by aperfilyev** [comment]
@Wanimal meanwhile you can use [this](https://github.com/akarnokd/RxJava2Interop)

**Comment by Wanimal** [comment]
Yes, thank you, good job.
