### ISSUE TITLE
Feature request: Adding NetworkInfo in Connectivity

### ISSUE THREAD

**Issue by probepark** [pwittchen/ReactiveNetwork#151]
Can i get NetworkInfo's typeName and subtypeName like WIFI?

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue.
Right now it's not possible, but we can add such feature. It could be useful.

Regards,
Piotr

**Comment by probepark** [comment]
@pwittchen 
Thank you.

**Comment by pwittchen** [comment]
I took a look at [NetworkInfo](https://developer.android.com/reference/android/net/NetworkInfo.html) class and current implementation of `Connectivity` class. I think, I'd rather create additional methods like `getSubtype()`, `getSubtypeName()`, etc. which will wrap NetworkInfo methods instead of exposing `getNetworkInfo(context)` method. Android SDK allows `NetworkInfo` to be `null` and I don't want to return `null` values in ReactiveNetwork library. Unfortunately, we cannot use Java 8 and `Optional` right now on Android and I don't want to add Guava dependency just for that. To sum up, wrapping these getters and assigning default initial values to them will be the safest option for now.

**Comment by probepark** [comment]
@pwittchen 
I think so. wrapped class of NetworkInfo is great idea.
It will be safe.

**Comment by pwittchen** [comment]
Change is pushed to branch `issue-151`. I'll leave this PR for a while and browse it later once again before the merge. Maybe someone will perform a code review, so I'll be sure that everything is fine. After that, this change will be merged into the `master` branch.

**Comment by Kisty** [comment]
LGTM. Can't see any problems. 👍

**Comment by pwittchen** [comment]
Thanks for your review @Kisty!

**Comment by probepark** [comment]
LGTM!

**Comment by pwittchen** [comment]
Changes are merge to `master` branch. They'll be available in the next release.
