### ISSUE TITLE
[Question] How would you filter only the network state change

### ISSUE THREAD

**Issue by nksaroj** [pwittchen/ReactiveNetwork#169]
1. With the ReactiveNetwork Library. It's starts firing on resume if network is available. 
That's what I can see in your sample. But I am interested only when there is a state change.
ON--> OFF or OFF--> ON not interested in if there is no state change.

2. I am getting the attached error for the following line of code in the filter. 

   <img width="1135" alt="screen shot 2017-04-26 at 10 58 43 pm" src="https://cloud.githubusercontent.com/assets/3455448/25435684/36e6c15c-2ad4-11e7-9849-496368c51975.png">

   .filter(ConnectivityPredicate.hasState(NetworkInfo.State.CONNECTED))
    .filter(ConnectivityPredicate.hasType(ConnectivityManager.TYPE_WIFI))

Appreciate your help!

**Comment by nksaroj** [comment]
I hope PR #168 should fix  the 2nd issue. If you are happy can you able to merge quickly

**Comment by pwittchen** [comment]
Thanks for reporting this issue. I'm going to merge #168 soon if there won't be any issues with that.

**Comment by nksaroj** [comment]
Would you please help with question:1

With the ReactiveNetwork Library. It's starts firing on resume if network is available.
That's what I can see in your sample. But I am interested only when there is a state change.
ON--> OFF or OFF--> ON not interested in if there is no state change.

**Comment by pwittchen** [comment]
@nksaroj Currently, by design library creates an observable, which starts with the initial connectivity state - connected or disconnected depending on the state of the device. It's done in all network observing strategies. In most of the apps, it's useful to know, if we're connected or not when activity or service starts. Moreover, users may see the false result if we eliminate this functionality in the following scenario (when subscription/disposable is in the activity):

1. User starts the app
2. Connectivity changes
3. App goes to the background
4. Connectivity changes
5. App goes to the foreground
6. User sees wrong information about connectivity because it keeps information about last connectivity state marked in the UI and it wasn't updated in `onResume()`

Of course, we can customize it in the future if there's such need.

**Comment by pwittchen** [comment]
I checked RxJava documentation. You can also skip first, default item, with [skip](http://reactivex.io/documentation/operators/skip.html) operator from RxJava. With `skip(1)`, you should achieve your goal and the app will be notified about connectivity change only, when it really changes without the initial connectivity value.

**Comment by nksaroj** [comment]
Thanks @pwittchen . I will give go 🥇
