### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by lion4ik** [pwittchen/ReactiveNetwork#173]
Look at 

```java
 private static NetworkInfo getNetworkInfo(final Context context) {
    final String service = Context.CONNECTIVITY_SERVICE;
    final ConnectivityManager manager = (ConnectivityManager) context.getSystemService(service);
    return manager.getActiveNetworkInfo();
  }
```
from ```Connectivity``` class
getActiveNetworkInfo() can return null, so this code will crash with NullPointerException

What do you think about this?

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. I'm away from home without a laptop right
now and I cannot check it immediately. I'm replying from my phone. I'm
aware of this problem and it should be handled by the library gracefully as
far as I know. I'll take a look on details later.

17.05.2017 12:58 PM "Alexey" <notifications@github.com> napisał(a):

**Comment by pwittchen** [comment]
@lion4ik Take a look at this line:
https://github.com/pwittchen/ReactiveNetwork/blob/RxJava2.x/library/src/main/java/com/github/pwittchen/reactivenetwork/library/rx2/Connectivity.java#L45

Whole method looks like that:

```java
  public static Connectivity create(Context context) {
    Preconditions.checkNotNull(context, "context == null");
    final NetworkInfo networkInfo = getNetworkInfo(context);
    return (networkInfo == null) ? create() : create(networkInfo);
  }
```

When we're using `NetworkInfo` class from Android SDK inside `Connectivity` class from the library, `NullPointerException` will not occur, because the library code and factory methods are aware of that. 
Developers simply should not pass `null` `Context` to the `Connectivity` object and everything should be fine. Moreover, library notifies the user about the wrong argument with an appropriate exception.
In addition, method quoted by you is private and not exposed in the library API.

**Comment by Kisty** [comment]
OK, so perhaps add a `@NonNull` annotation to the `Connectivity#create(Context)` method?

**Comment by pwittchen** [comment]
It's related to different thing than this issue, but we can add it.

22.05.2017 3:57 PM "Timothy Kist" <notifications@github.com> napisał(a):

**Comment by lion4ik** [comment]
Yeah, probably there is no problem in this code. It just confused me a bit. Now, I clarified it, thanks.

**Comment by pwittchen** [comment]
Ok, thanks for the reply.
