### ISSUE TITLE
Duplicate entry:  com/github/pwittchen/reactivenetwork/library/BuildConfig.class

### ISSUE THREAD

**Issue by yshrsmz** [pwittchen/ReactiveNetwork#195]
I encountered this error while migrating my app to RxJava2.
I imported both ReactiveNetwork & ReactiveNetwork2(just because I was in migration process), and got this.

It seems like you forgot to update package name in AndroidManifest.xml?

**Comment by pwittchen** [comment]
Hi,

In the RxJava2.x version I've changed package from `com.github.pwittchen.library` to `com.github.pwittchen.library.rx2` to distinguish classes from different artifacts. I think you shouldn't keep both library versions in the application at the same time because it may cause code conflicts like yours. It's better to remove RxJava1.x version and then add RxJava2.x version, update imports and adjust the code. Migration should be really simple. Take a look at the migration commit for this library, where sample app was migrated as well: https://github.com/pwittchen/ReactiveNetwork/commit/f35c869eec7622f15213337532c4c3d01d7bc0ba (check `MainActivity.java` file).

Regards,
Piotr

**Comment by yshrsmz** [comment]
Thanks for your quick response.

Yes I'm going to use v2 and remove v1.

I just wanted to report that this line should be updated as well.
https://github.com/pwittchen/ReactiveNetwork/blob/RxJava2.x/library/src/main/AndroidManifest.xml#L2

**Comment by pwittchen** [comment]
Ok, thanks. We'll update it.
