### ISSUE TITLE
Overriding host always returns false for isConnected

### ISSUE THREAD

**Issue by emitchel** [pwittchen/ReactiveNetwork#203]
I'm trying to verify my "internet" connection by attempting to connect to an internal site `http://{company name}.org`. Using the default values that `observerInternetConnectivity()` would use (besides the host) it always returns `false` for `isConnected`. 

Is it because this site isn't returning 204 like what the default `"http://clients3.google.com/generate_204"` would? Or am I missing something completely obvious?

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. If you're using the custom host for checking the Internet connection, I suggest using `SocketInternetObservingStrategy` instead of `WalledGardenInternetObservingStrategy`, which was added in the latest release and applied as the default. `WalledGardenInternetObservingStrategy` marks server response as valid, when the response code is `204`. You can customize library with the following `Observable`:

```java
Observable<Boolean> observeInternetConnectivity(
  final InternetObservingStrategy strategy, 
  final int initialIntervalInMs, final int intervalInMs, final String host, 
  final int port, final int timeoutInMs, final ErrorHandler errorHandler)
```

or with `Single`:

```java
Single<Boolean> checkInternetConnectivity(
  InternetObservingStrategy strategy, 
  String host, int port, int timeoutInMs, 
  ErrorHandler errorHandler)
```

In your case, probably, it'll look like that:

```java
ReactiveNetwork.observeInternetConnectivity(
  new SocketInternetObservingStrategy(), 0, 2000, 
  "www.yourcompany.org", 80, 2000, new DefaultErrorHandler())
  .subscribeOn(...)
  .observeOn(...)
  .subscribe(...);
```

We can think of adding to the API the additional method, with just `strategy` and `host` as parameters and remaining values as default because it could be a common use case.

Regards,
Piotr

**Comment by emitchel** [comment]
Thanks @pwittchen this worked, but I also figured out that if I prepend my host with `http://` it doesn't work. Looking through the source code, I dont know why it would cause a problem. Either way, once I went with `mycompany.org` instead of `http://mycompany.org` I was good to go (along with using `SocketInternetObservingStrategy()`)

**Comment by pwittchen** [comment]
The issue with `http://` may be caused by [`java.net.InetSocketAddress`](https://docs.oracle.com/javase/7/docs/api/java/net/InetSocketAddress.html) class. Nevertheless, it may be a good idea to handle both cases (with and without `http://`).

**Comment by emitchel** [comment]
Sounds good, consider this issue closed.
