### ISSUE TITLE
Repeating task with repeatWhen()

### ISSUE THREAD

**Issue by prokash-sarkar** [pwittchen/ReactiveNetwork#208]
From the following setup I'm unable to repeat a task,

```java
networkDisposable = ReactiveNetwork.observeNetworkConnectivity(getApplicationContext())
                .subscribeOn(Schedulers.io())
                .switchMap(connectivity -> {
                    if (connectivity.getState().equals(NetworkInfo.State.CONNECTED)) {
                        return yahooService.yqlQuery(query, env).toObservable();
                    } else {
                        return Observable.empty();
                    }
                })
                .map(m -> m.getQuery().getResults().getQuote())
                .flatMap(Observable::fromIterable)
                .map(StockUpdate::create)
                .observeOn(AndroidSchedulers.mainThread())
                .repeatWhen(o -> o.delay(10, TimeUnit.SECONDS))
                .subscribe(stockUpdate -> {
                    mStockDataAdapter.add(stockUpdate);
                });
```
Seems like the `.repeatWhen()` is unable to return the observable?

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. I'll have to take a look at your use case.

I see one problem here. You are trying to repeat the observation of network connectivity. Please note, that this Observable is using Android BroadcastReceiver under the hood and subscriber will get notification only when connectivity changes. Only in this case, an event will be emitted. There's no polling or immediate check of the connectivity, so I'm not sure if emitted event will be propagated here within a given time interval.

Regarding your question, according to the RxJava source code, `.repeatWhen()` should return an Observable. Here's the reference: https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L9175. Maybe there's a problem in your stream composition. E.g. `.observeOn()` could be swapped with `.repeatWhen()`. I'm not sure about that and I'm just guessing because I haven't tested that example in the code yet.

Regards,
Piotr

**Comment by pwittchen** [comment]
Question is pretty old. There's no further discussion, so we can close it.
