### ISSUE TITLE
RxJava2 Migration Issues

### ISSUE THREAD

**Issue by marcoRS** [pwittchen/ReactiveNetwork#248]
Hello we previously had the following code when using the RxJava 1 version:

```java
  new ReactiveNetwork().enableInternetCheck()
                         .observeConnectivity(this)
                         .filter(status -> status == ConnectivityStatus.OFFLINE
                                           || status == ConnectivityStatus.WIFI_CONNECTED_HAS_NO_INTERNET)
                         .compose(new AppScheduler<>())
                         .compose(bindToLifecycle())
```
But with the Api change for RxJava2 we cannot find the equivalent.

**Comment by pwittchen** [comment]
Hi @marcoRS.

According to my docs, you were using version 0.2.0 or earlier, which was released 2 years ago. A lot of code was changed since that time.

In the latest version of the library, you can observe network connectivity (e.g. Wifi, mobile, etc.) with method:

```java
ReactiveNetwork.observeNetworkConnectivity(context)
```

It doesn't check Internet connectivity. Just network connectivity (network can be disconnected from the Internet).

If you want to observe Internet connectivity continuously, you can use the following method:

```
ReactiveNetwork.observeInternetConnectivity()
```

It will ping google.com every two seconds (of course, you can customize it as you want).

If you want to check Internet connectivity **once**, you can use the following method:

```
ReactiveNetwork.observeInternetConnectivity()
```

If you want to observe network connectivity and then check Internet connectivity (chain two streams), please check the following section in the documentation:

https://github.com/pwittchen/ReactiveNetwork#chaining-network-and-internet-connectivity-streams

You can also check sample app here: https://github.com/pwittchen/ReactiveNetwork/tree/RxJava2.x/app

I hope, it will help you during the migration. In the case of further issues or doubts, you can post a comment here :).

Regards,
Piotr

**Comment by pwittchen** [comment]
I didn't get any new response for a long time, so I guess this problem was clarified.
