### ISSUE TITLE
[Question] Does observeInternetConnectivity creates a Hot or Cold Observable?

### ISSUE THREAD

**Issue by luccasmaso** [pwittchen/ReactiveNetwork#253]
I'm calling `ReactiveNetwork.observeInternetConnectivity()` all over my code and I would like to know if each time I create this observable it will open new socket connection or polling walled garden host depending on the Strategy.

Reference: https://medium.com/@benlesh/hot-vs-cold-observables-f8094ed53339#5692

Thanks

**Comment by pwittchen** [comment]
Since version 0.11.0 `WalledGardenInternetObservingStrategy` is the default strategy for observing internet connection. Before 0.11.0 it was opening a Socket. Of course, you can customize it.

Reference: https://github.com/pwittchen/ReactiveNetwork/blob/RxJava2.x/CHANGELOG.md#v-0110

Hint: If you are using this call in many places, I'd suggest to hide it behind an interface for the easy customizations and testing in the future or put it to the instance of `Application` and broadcast results to the other parts of the app. Nevertheless, it's an issue related to app design not the library itself.

Regards,
Piotr

**Comment by luccasmaso** [comment]
Thank for the response. But if I use the socket strategy will every `observeInternetConnectivity` create a new socket connection?

**Comment by pwittchen** [comment]
In `SocketInternetObservingStrategy` it should create new socket connection, because new instance of `Socket` object is created there. After each check, socket connection is closed if there's no exception. You can browse the source code, if you want to know more details.
