### ISSUE TITLE
when i open Strict Mode in Android Oreo, it keeps show error like:Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage. How can i solve this problem?

### ISSUE THREAD

**Issue by SunJenry** [pwittchen/ReactiveNetwork#254]
![image](https://user-images.githubusercontent.com/14819974/35669367-d251c89e-076f-11e8-87d5-6f53e667b876.png)

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting that. It can be fixed in the similar way as here: https://github.com/square/okhttp/pull/842.

Other references:
- https://developer.android.com/training/efficient-downloads/efficient-network-access.html?hl=es
- https://stackoverflow.com/questions/36696447/how-to-get-trafficstats-from-a-specific-thread

I'll take a look on that.

**Comment by SunJenry** [comment]
Thanks a lot, your comment really helps me.Fix this problem by adding the code in the picture.
![image](https://user-images.githubusercontent.com/14819974/35716192-2117dcb4-0812-11e8-9f6b-47b84e768ce2.png)
