### ISSUE TITLE
Mock ReactiveNetwork

### ISSUE THREAD

**Issue by djohannot** [pwittchen/ReactiveNetwork#275]
Hi guys,
I have (maybe) a stupid question, but i take the risk to ask for it.

I want to use your project in our application, but I am afraid I will not be able to mock your library as all the methods are static from the ReactiveNetwork class.

Do you have a solution for it? How can mock the response from the methods of that class without using a specific library like PowerMock?

Thanks for your help

David

**Comment by pwittchen** [comment]
Hi,

I also had doubts if I should made these methods static, but I followed approach from the original RxJava library, where they do the same. Please note, it's library - not a framework, so you're not forced to use it in any particular way. My suggestion is to hide library behind appropriate interface, which can be mocked in your project. E.g.

```java
interface NetworkObserver {
  Observable<Connectivity> observeNetwork(Context context);
}
```

```java
class DefaultNetworkObserver implements NetworkObserver {
  @Override
  Observable<Connectivity> observeNetwork(final Context context) {
    return ReactiveNetwork.observeNetworkConnectivity(context);
  }
}
```

Now, you can use interface in your project and inject implementation manually or via DI framework/library. Next, you can mock an interface in your tests. Such approach is flexible because you can easily change network monitoring strategy, add configuration and so on in the future in case you need it.

Regards,
Piotr

**Comment by pwittchen** [comment]
I've got no further response in 20 days, so I assume my reply is sufficient and an issue can be closed.
