### ISSUE TITLE
Accessing "state" from Connectivity is private (kotlin)

### ISSUE THREAD

**Issue by zdunaisky-chwy** [pwittchen/ReactiveNetwork#288]
Accessing Connectivity state like this throws an error: `Cannot access state: it is private in "Connectivity"`

```
.subscribe { connectivity ->
    if (connectivity.state == NetworkInfo.State.CONNECTED) {
        // do stuff
    }
}
```
^^ this will not compile but no error is shown in Android Studio.

However, accessing state as you have in the kotlin example shows the following error (but compiles fine):

![screen shot 2018-07-21 at 2 50 45 pm](https://user-images.githubusercontent.com/5703278/43039160-95016ad8-8cf5-11e8-9960-9db88d199744.png)

**Comment by pwittchen** [comment]
Thanks for reporting this issue. It should work fine. I'll verify this.

sob., 21 lip 2018, 20:57 użytkownik Zachary Dunaisky <
notifications@github.com> napisał:

**Comment by pwittchen** [comment]
Class variable `state` is private, but method `state()` is public, so it should be accessible from any place. Maybe Kotilin is confused when I have the same method name as a variable name. I'll check it again.

**Comment by pwittchen** [comment]
In the sample Kotlin app, I've imported library from the Maven Central Repository instead of a local module and tried to access `state()` method. I couldn't see any errors.

![gnome-shell-screenshot-ke2tmz](https://user-images.githubusercontent.com/695319/43041023-b29435b2-8d54-11e8-93e6-edc533e029c7.png)

Please, ensure you're using the latest version of the library. Previously, this method was called `getState()`. Now, it's `state()`.

**Comment by zdunaisky-chwy** [comment]
SO STRANGE.

Tried again today after some cache invalidations, restarts, cleans, etc. Seems to be working fine now. 

Thank you for looking into this and the for the awesome lib!

**Comment by pwittchen** [comment]
Great to hear you resolved the problem!

Cheers,
Piotr

pon., 30 lip 2018, 21:21 użytkownik Zachary Dunaisky <
notifications@github.com> napisał:
