### ISSUE TITLE
Unable to provide different host because of 204 code

### ISSUE THREAD

**Issue by lectricas** [pwittchen/ReactiveNetwork#302]
Hi.
There is no way you can check true connection with SocketInternetObservingStrategy.
Try to made a wrong proxy for your wifi connection - wifi is connected by no internet is available.
Still `checkInternetConnectivity returns true`
So, in this case I have to use WalledGardenInternetObservingStrategy with httpurlconnection which checks 
http://clients3.google.com/generate_204 this page for 204 code.
I don't have this page on my backend, so I'm unable to use in properly. 
Why not just to check for 200?
With 200 code it works like a charm. 
Thank you.

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting that. `WalledGardenInternetObservingStrategy` is kind of specific use case. I think, one way to solve your problem will be creating additional setting, where you can set desired HTTP response like 200 (or anything else) instead of 204. That should be easy fix.

Regards,
Piotr

**Comment by pwittchen** [comment]
I've added `httpResponse(int)` method in `InternetObservingSettings` in PR #303. Documentation was updated too. This update breaks the API. It will be available in the next release.
