### ISSUE TITLE
connectivity.extraInfo() returns null on android P 

### ISSUE THREAD

**Issue by lfei1789** [pwittchen/ReactiveNetwork#311]
i use  WifiManager.getConnectionInfo() is ok

**Comment by pwittchen** [comment]
Hi @lfei1789,

Can you explain your issue? Method `connectivity.extraInfo()` does not have to return anything. You can get many information about the connection from the `Connectivity` object. Is something important missing there?

Regards,
Piotr

**Comment by lfei1789** [comment]
first, thank you for your reply
android 8.1 and lower, NetworkInfo.getExtraInfo() you can get wifi ssid,but android P  NetworkInfo.getExtraInfo() is null
thanks again

**Comment by pwittchen** [comment]
Unfortunately, we don't have any influence on the value returned by `NetworkInfo.getExtraInfo()`.
Now, we cannot get `WifiInfo` from the `Connectivity` object because we can have many types of connection (not only Wifi). I think we can add a method, which returns `WifiInfo` object basing on active network to `Connectivity` object because it may be useful. In case of other connection types, it can simply return `null`. It also should be marked with appropriate annotation and documented. After that, you'll be able to get SSID via `wifiInfo.getSSID()` method.

**Comment by pwittchen** [comment]
You can get info about WiFi connection as follows:

```java
WifiManager manager = (WifiManager) getSystemService(Context.WIFI_SERVICE);
WifiInfo connectionInfo = manager.getConnectionInfo();
```

and it requires `ACCESS_WIFI_STATE` permissions in `AndroidManifest.xml` file. I've decided not to add this to the library to avoid adding additional permissions, which may not be required by all apps using this library. If you want to have reactive API specific for WiFi connections, then you can have a look at [ReactiveWifi](https://github.com/pwittchen/ReactiveWifi) library.

**Comment by lfei1789** [comment]
I have solved the problem, as you said  ,  but thank you very much

**Comment by pwittchen** [comment]
Ok, thanks for the reply @lfei1789 !
