### ISSUE TITLE
Will there be a version for Kotlin Flow ?

### ISSUE THREAD

**Issue by Egi10** [pwittchen/ReactiveNetwork#466]
I now have a project using Kotlin Flow, so I wanted to ask if this will be migrated to Kotlin Flow in the future?

Or according to this issue: #368 

Thanks

**Comment by pwittchen** [comment]
Hi @Egi10,

This library heavily relies on RxJava, so Kotlin Flow version would require rewriting it from the scratch. I think it makes more sense to create another project like that, but based on Kotlin Flow instead of rewriting this library because there are still projects out there which rely on RxJava and not everyone migrates to Kotlin Flow. You can search for similar projects based on Kotlin Flow. You can see other people already created something like that and in the discussion in #368 you can find links to existing projects.

Regards,
Piotr

**Comment by Egi10** [comment]
thank you very much
