### ISSUE TITLE
Question: nested calling

### ISSUE THREAD

**Issue by kdani41** [pwittchen/ReactiveNetwork#49]
Hi,

First off amazing library!!!. Thanks for devoting your time :+1: 
My question might not be specific to your library but I'm stuck in this small problem. I will really appreciate if you can help.

So, basically what i want to achieve is according to the internet connection I want to fire the api call and to do this I think I have to combine 2 observables (one is from your library and one is mine from the api that i'm using).

My attempt: 

```
new ReactiveNetwork().observeConnectivity(context)
.flatMap(new Func1<ConnectivityStatus, Observable<JSONObject>>() {
            // I want to access subscriber in here.
            @Override
            public Observable<JSONObject> call(ConnectivityStatus connectivityStatus) {

                return null;
            }
        })
.observeOn(AndroidSchedulers.mainThread())
.subscribeOn(Schedulers.io())
// I want to use onNext, onError 
.subscribe(this);
```

Not sure if I'm doing this right but will really appreciate if you can help..
Thanks again for devoting your time!!

**Comment by pwittchen** [comment]
Hi,

Thanks for your question! It's actually not related to this library, but to RxJava and Reactive Programming. I think you should use [zip()](http://reactivex.io/documentation/operators/zip.html) operator from RxJava library in order to combine two or more Observables. This will allow you to fire API call when internet connection is available without breaking a chain. When I find some time, I'll prepare an example of that solution. In the meantime, you can try to experiment with it by yourself.

Regards,
Piotr

**Comment by Rainer-Lang** [comment]
@pwittchen I'm also interested in an example of your lib combined with retrofit.

**Comment by pwittchen** [comment]
@kdani41 @Rainer-Lang I was quite busy, so I haven't published it yet. Sorry for a long delay. I'm also working on a few updates in this project. I'll try to publish this sample ASAP and then notify you in the comments in this issue.

**Comment by pwittchen** [comment]
I've added simple examples with nested calling with OkHttp and Retrofit here:
https://github.com/pwittchen/ReactiveNetwork#integration-with-other-libraries

If you're using other libraries, they can be integrated in the similar manner.
