### ISSUE TITLE
How to detect if my mobile data is enabled, but don't have internet connection

### ISSUE THREAD

**Issue by narendrakothamire** [pwittchen/ReactiveNetwork#51]
Hi

Thanks for this lib bro and for making it reactive
but I have an issue how do i detect if i have internet or not when my mobile data is enabled

**Comment by pwittchen** [comment]
Hi,

I assumed that when you're connected to mobile network (mobile data transfer is activated), you already have an internet access. I don't know if it's possible that you have mobile data transfer activated and there's no internet access. Have you encountered such situation?

**Comment by narendrakothamire** [comment]
Yes in some areas you might have your mobile data enabled but there may not be internet or there is no tower signal

**Comment by pwittchen** [comment]
Ok, I'll take a look on that when I find some time.

**Comment by wrparrish** [comment]
I run into this issue often (In subways, and other areas where there is no signal at all) and it would be great to have a bundled solution with your library.  We've been using it in production for almost a year, and it's been great.

**Comment by pwittchen** [comment]
@narendrakothamire @wrparrish Ok. If it's an issue I'll work on that. Thanks for your comments!

**Comment by pwittchen** [comment]
Sorry that you have to wait for a long time. This is actually my side project, so I cannot work on it full time. I'm working on that issue. I had some problems with obtaining deterministic results with network monitoring merged with Internet connectivity checking via `zip()` operator from RxJava.

Moreover, I see the following scenario:
1. device is connected to mobile or WiFi network
2. given network has an Internet access
3. user is still connected to the network, but Internet access is lost in the network and user is not notified because network monitoring is based on BroadcastReceivers

What do you think about the following improvement:
- remove `enableInternetCheck()` method because it does not fit your needs and sometimes does not work properly
- remove `WIFI_CONNECTED_HAS_INTERNET` and  `WIFI_CONNECTED_HAS_NO_INTERNET` statuses
- add a new method `Observable<Boolean> observeInternet()`
- add another, more customizable new method `Observable<Boolean> observeInternet(final int interval, final String host, final int port, final int timeout)`

Then `observeConnectivity()` will be used only for monitoring connectivity with the networks and `observeInternet()` will be used for monitoring connectivity with the Internet. The drawback of the new method is the fact that it will perform socket connection to a remote host, which will consume some data transfer and it will need to do it within a given interval (default can be 1 second). It will be less efficient than `observeConnectivity()` method, but you will be sure that the Internet is available. With that solution, you can choose, which Observable is more appropriate for your use cases.

Later, in the next iteration, we can consider merging two mentioned Observables, because it's not that easy as I thought or I may be doing something wrong.

Please, let me know, what you think about that and we can add some improvements.

**Comment by pwittchen** [comment]
Maybe more appropriate method names would be as follows:
- `Observable<ConnectivityStatus> observeNetworkConnectivity()` (instead of `observeConnectivity()`)
- `Observable<Boolean> observeInternetConnectivity()` (new method)

Then, names are would be explicit and meaningful.

**Comment by wrparrish** [comment]
I like that!

the new method that does some light interval socket communication sounds perfect.  It would quickly catch a loss in connection ( IE  going underground to get into the subway ).    

I do also find the wifi_connected_has_internet  and  wifi_connect_has_no_internet  very useful,  but if they need to be removed i can work around that.   Thanks for taking the time to address this request.

**Comment by pwittchen** [comment]
Ok. I'm planning to add such improvements in the release of v. 0.3.0 ➡️ #53.
You'll still be able to use `WIFI_CONNECTED` and `MOBILE_CONNECTED` status.

As far as I see `WIFI_CONNECTED_HAS_INTERNET` is not checking real Internet connection what has reported some time ago in one of the issues in my GitHub projects. That's why I'm going to remove this status.

**Comment by pwittchen** [comment]
Changes are now available on `internet-check-fix` branch. When CI build will pass and I will test it, then it'll be merged to the master branch. I'll appreciate any suggestions, comments and code reviews in this Pull Request.

**Comment by pwittchen** [comment]
Updates are merged to the master branch and documentation in the `README.md` file is updated. New features will be available in release 0.3.0.
