### ISSUE TITLE
Add example of library usage with Retrofit

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/ReactiveNetwork#68]
Add example of library usage with Retrofit and update documentation.

It's related to issue #49.

**Comment by YuriHeupa** [comment]
Also waiting for this!

**Comment by Rainer-Lang** [comment]
Me too.

**Comment by pwittchen** [comment]
I remember about that. I just need to find some time for this. Recently, I've bumped library version and added new updates like support for Android N and better network monitoring, which are crucial enhancements in this project. Providing this example will be next on my list. :)

**Comment by epicstar** [comment]
I'm currently using this library with Retrofit + RxJava using `Observable#retryWhen()` using one of the older versions of ReactiveNetwork: https://github.com/rectangle-dbmi/Realtime-Port-Authority/blob/7.0.2/app/src/main/java/rectangledbmi/com/pittsburghrealtimetracker/BusMapFragment.java#L555

This will work based on two criteria:

1. the restish API cannot be reached (the retrofit observable throws an IOException)
2. when it is determined that this is due to a lost data connection on the phone side (though there is one situation where this doesn't work and haven't had the time to fix it).

Currently, the rest of the code is a bit scary (because of my failure to use one of the MVVM patterns of Android... which will be fixed). I will be changing to the newer version of the library later AND will be using the internetConnectivityObservable when I have the time to change it.

**Comment by pwittchen** [comment]
I've added a simple example here: https://github.com/pwittchen/ReactiveNetwork#integration-with-retrofit.
It's valid for RxJava2.x version.
