### ISSUE TITLE
Issue with fragments

### ISSUE THREAD

**Issue by renegens** [pwittchen/ReactiveNetwork#86]
Hello, 

Great work on this lib. I am using it in onResume with observeInternetConnectivity() and are creating my subscriptions in onStart. This creates although a problem that even if I have internet the boolean callback is triggered and is showing that the user has internet. Is there any other way except with an another boolean to track the state?

**Comment by pwittchen** [comment]
Actually, this problem is related to Activity and Fragment lifecycle. When Activity or Fragment are created or resumed, the subscription is started and then you'll get a notification. If you don't want to be notified every time when Activity or Fragment is resumed I see two solutions for now:
- Save information about connectivity somewhere (e.g. to SharedPreferences) and notify the user whenever it changes. You can use my another project called [prefser](https://github.com/pwittchen/prefser), which allows monitoring changes in SharedPreferences with RxJava 1.x. Then you can start Internet subscription even in a Service.
- Start Internet subscription in a Service and pass the event to the Fragment or Activity whenever connection state changes. Service is independent of Activity and Fragment lifecycle, so you don't have to care about them in this solution. You can pass this data in many ways - e.g. via Event Bus like [otto](https://github.com/square/otto) or implement [RxBus suggested by otto developers](http://blog.kaush.co/2014/12/24/implementing-an-event-bus-with-rxjava-rxbus/) (I would choose this option) or in a different way.

Regards,
Piotr

**Comment by renegens** [comment]
Thanks for the reply. I went ahead and did it the second solution. I think it's more robust in case I need in the future to add something which has a scope of the whole app.
